name: care360
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_firebase_admin: ^0.4.0
  dart_frog: ^1.1.0
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  json_serializable: ^6.7.1
  logger: ^2.5.0
  uuid: ^4.5.0



dev_dependencies:
  build_runner: ^2.4.13
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
