name: care360
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  uuid: ^4.5.0
  firedart: ^0.9.8
  dartz: ^0.10.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

dev_dependencies:
  mocktail: ^1.0.3
  build_runner: ^2.4.13
  test: ^1.25.5
  very_good_analysis: ^5.1.0
